apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: post-service
  name: post-service
spec:
  selector:
    matchLabels:
      io.kompose.service: post-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: post-service
    spec:
      containers:
        - image: tendeza/sem6-post-service:latest
          name: post-service
          ports:
            - containerPort: 8081
          resources:
            limits:
                cpu: "1000m"
                memory: "1000Mi"
      restartPolicy: Always
status: {}
