name: azure-post-service
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: Sem-6
    AZURE_CONTAINER_REGISTRY: acrworkflow1714126575894
    CLUSTER_NAME: DailyGrind
    CLUSTER_RESOURCE_GROUP: Sem-6
    CONTAINER_NAME: image-workflow-1714126575894
    DEPLOYMENT_MANIFEST_PATH: |
        ./Manifest/post-service-deployment.yaml
        ./Manifest/post-service-service.yaml
jobs:
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/use-kubelogin@v1
              name: Set up kubelogin for non-interactive login
              with:
                kubelogin-version: v0.0.25
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: tendeza/sem6-post-service
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
